Repository spack/spack-tutorial, pull requests merged in 2019-11, with the labels that each got.

#10 Change pygments style to default
  conf.py
Labels: formatting

#20 Basic Installation: updated output to Ubuntu 18.04
  tutorial_basics.rst
Labels: documentation

#22 Module Files: updated output to Ubuntu 18.04
  tutorial_modules.rst
Labels: documentation

#24 Developer workflow: switched package from HDF5 to HWLOC
  tutorial_developer_workflows.rst
Labels: documentation, enhancement

#25 Document use of the maintainers field
  tutorial/examples/0.package.py
  tutorial/examples/1.package.py
  tutorial/examples/2.package.py
  tutorial/examples/3.package.py
  tutorial/examples/4.package.py
  tutorial/examples/5.package.py
  tutorial_packaging.rst
Labels: documentation

#23 Configuration: updated output to Ubuntu 18.04
  tutorial_configuration.rst
Labels: documentation

#26 Update Package Creation Tutorial for SC19
  tutorial/examples/0.package.py
  tutorial/examples/1.package.py
  tutorial/examples/2.package.py
  tutorial/examples/3.package.py
  tutorial/examples/4.package.py
  tutorial/examples/5.package.py
  tutorial_packaging.rst
Labels: documentation

#27 Package Creation: updated output to Ubuntu 18.04
  tutorial_packaging.rst
Labels: documentation

#28 Last minute updates to Configuration Tutorial
  tutorial_configuration.rst
Labels: documentation

#32 Fix dot command usage during Basic Installation Tutorial
  tutorial_basics.rst
Labels: bug

#36 Add missing uninstall command to Developer Workflows Tutorial
  tutorial_developer_workflows.rst
Labels: bug

#34 Add missing end quotes to Spack Stacks Tutorial
  tutorial_stacks.rst
Labels: bug
