Repository spack/spack-tutorial, pull requests merged in 2020-11, with the labels that each got.

#75 Fix "recursive" argument in "find_libraries" example.
  tutorial_advanced_packaging.rst
Labels: bug

#79 SC20 updates for Configuration Tutorial
  tutorial_configuration.rst
Labels: documentation

#77 SC20: Module Files Generation Tutorial
  outputs/modules.sh
  outputs/modules/lapack-conflict.out
  outputs/modules/lapack-hier.out
  outputs/modules/lmod-intro-avail.out
  outputs/modules/module-avail-1.out
  outputs/modules/module-avail-2.out
  outputs/modules/module-avail-3.out
  outputs/modules/module-avail-4.out
  outputs/modules/module-avail-5.out
  outputs/modules/module-avail-6.out
  outputs/modules/module-avail-7.out
  outputs/modules/module-avail-8.out
  outputs/modules/module-show-1.out
  outputs/modules/module-show-2.out
  outputs/modules/module-show-3.out
  outputs/modules/module-show-4.out
  tutorial_modules.rst
Labels: enhancement

#81 SC20 updates for Basics Tutorial
  outputs/basics.sh
  outputs/basics/list-py.out
  outputs/basics/uninstall-r-needed.out
  outputs/basics/uninstall-specific.out
  outputs/basics/uninstall-zlib.out
  tutorial_basics.rst
Labels: documentation

#82 Add additional changes to Config Tutorial
  tutorial_configuration.rst
Labels: documentation

#90 Added highlighting and expanded on stackstart
  outputs/packaging/configure-build-options.out
  tutorial_packaging.rst
Labels: documentation

#93 sc20 Revisions to scripting with spack
  outputs/scripting/spack-python-1.out
  outputs/scripting/spack-python-abstract.out
  outputs/scripting/spack-python-concrete.out
  outputs/scripting/spack-python-db-query-exclude.out
  outputs/scripting/spack-python-db-query-help.out
  outputs/scripting/spack-python-sans-intermediate.out
  tutorial_spack_scripting.rst
Labels: documentation

#96 Additional scripting tutorial refinements including fixes
  tutorial_spack_scripting.rst
Labels: documentation
